### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by currenjin** [mul-jil/image-processor#2]
- [x] 이미지 속 객체의 픽셀 계산 SEARCHING

Tasks
- [x] 사이즈 계산을 위한 클래스 생성
- [x] 요청을 위한 api 생성
- [x] 이미지 속 객체의 픽셀 계산
